version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:1.0.1
    container_name: opensearch-node1
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo security configuration
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./elk-config/custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./elk-config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./elk-config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - ./elk-config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      - ./elk-config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./elk-config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:1.0.1
    container_name: opensearch-node2
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./elk-config/custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./elk-config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./elk-config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - ./elk-config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      - ./elk-config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./elk-config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.0.1
    container_name: opensearch-dashboards
    restart: unless-stopped
    ports:
      - 444:443
    expose:
      - "443"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # must be a string with no spaces when specified as an environment variable
    volumes:
      - ./elk-config/custom-opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
  proservice-api:
    container_name: proservice-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped  
    ports:
      - 80:80 
      # - 443:443
    environment: 
      opensearch_username: ${opensearch_username}
      opensearch_password: ${opensearch_password}
      ca_path: ${ca_path}
      es_host: ${es_host}
      mqtt_username: ${mqtt_username}
      mqtt_password: ${mqtt_password}
      mqtt_url: ${mqtt_url}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      TOKEN_ENV: ${TOKEN_ENV}
      TZ: ${TZ}
      EVENT_INDEX: ${EVENT_INDEX}
      DOMAIN: ${DOMAIN}
    volumes: 
      - ./certs/gen/root-ca.pem:${ca_path}  
      - /etc/letsencrypt:/etc/letsencrypt
      - ./publickey:/etc/publickey
    networks:
      - opensearch-net  
    depends_on:
      - opensearch-node1
      - opensearch-node2  
      - database
  database:
    image: postgres:13
    restart: unless-stopped
    shm_size: "256mb"
    ports:
      - 127.0.0.1:5432:5432 
    environment:
      - POSTGRES_DB=$POSTGRES_DBNAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata/
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
  filebeat:
  database-data:

networks:
  opensearch-net:

configs:
  fb_config:
    file: $PWD/filebeat.yml  
